version: "3.9"
services:
  mongodb:
    container_name: egonon-mongodb
    image: mongo:5.0.8
    restart: always
    networks:
      - egonon-network
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ~/egononmount/conf/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/egononmount/data/mongodb/:/data/db
    environment:
      - MONGO_INITDB_DATABASE=EgoNon
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=EgoNonLiege2022!
  front:
    container_name: egonon-front
    image: egonon-webserver:0.1
    restart: always
    networks:
      - egonon-network
    ports:
      - "80:80"
    volumes:
      - ~/egononmount/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    container_name: egonon-app
    image: egonon-back:0.1
    restart: always
    networks:
      - egonon-network
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://egonon:egonon2022!@egonon-mongodb:27017/EgoNon
  filebrowser:
    container_name: egonon-filebrowser
    image: hurlenko/filebrowser
    restart: always
    user: "${UID}:${GID}"
    ports:
      - 8080:8080
    networks:
      - egonon-network
    volumes:
      - ~/egononmount/data/filebrowser/:/data
      - ~/egononmount/conf/filebrowser/:/config
    environment:
      - FB_BASEURL=/filebrowser
networks:
  egonon-network:
    driver: bridge